url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "" # the name of your site, e.g. ACME Corp.

plugins:
  - jekyll-tailwind-cli
  - jekyll-heroicons

heroicons:
  variant: "solid"
  default_class:
    { solid: "size-6", outline: "size-6", mini: "size-5", micro: "size-4" }
